version: "0.2"
dictionaryDefinitions:
  - name: dictionary
    path: dictionary.txt
    addWords: true
dictionaries:
  - dictionary
ignorePaths:
  - dictionary.txt
  - api-reference/custom-field-formats.mdx
  - api-reference/ids-handles-and-aliases.mdx
  - assets/
